CREATE DATABASE T_ShirtStore;
USE T_ShirtStore;

CREATE TABLE Empresas(
	EmpresaId INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Perfis(
	PerfilId INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE Usuarios(
	UsuarioId INT PRIMARY KEY IDENTITY NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(MAX) NOT NULL,
	Perfil VARCHAR(25) FOREIGN KEY REFERENCES Perfis(Nome) NOT NULL,
	Empresa VARCHAR(255) FOREIGN KEY REFERENCES Empresas(Nome)
);
select * from Usuarios;
CREATE TABLE Tamanhos(
	TamanhoId INT PRIMARY KEY IDENTITY NOT NULL,
	Sigla VARCHAR(5) UNIQUE NOT NULL,
	Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Cores(
	CorId INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Camisetas(
	CamisetaId INT PRIMARY KEY IDENTITY NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
	Cor VARCHAR(255) FOREIGN KEY REFERENCES Cores(Nome) NOT NULL,
	Quantidade SMALLINT NOT NULL,
	Marca VARCHAR(255) FOREIGN KEY REFERENCES Empresas(Nome) NOT NULL
);

CREATE TABLE Estoque(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	CamisetaId INT FOREIGN KEY REFERENCES Camisetas(CamisetaId),
	Tamanhos VARCHAR(5) FOREIGN KEY REFERENCES Tamanhos(Sigla) NOT NULL,
	Cores VARCHAR(255) FOREIGN KEY REFERENCES Cores(Nome) NOT NULL
);
