CREATE DATABASE T_AutoPecas;

USE T_AutoPecas;

CREATE TABLE Pecas(
	PecaId INT PRIMARY KEY IDENTITY NOT NULL,
	PecaCodigo INT UNIQUE NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
	Peso FLOAT NOT NULL,
	PrecoCusto MONEY NOT NULL,
	PrecoVenda MONEY NOT NULL,
	FornecedorId INT FOREIGN KEY REFERENCES Fornecedores(FornecedorId)NOT NULL
);

CREATE TABLE Usuarios(
	UsuarioId INT PRIMARY KEY IDENTITY NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(30) NOT NULL
);

CREATE TABLE Fornecedores(
	FornecedorId INT PRIMARY KEY IDENTITY NOT NULL,
	Cnpj VARCHAR(20) UNIQUE NOT NULL,
	RazaoSocial VARCHAR(255) NOT NULL,
	NomeFantasia VARCHAR(255) NOT NULL,
	Endereco VARCHAR(255) NOT NULL,
	UsuarioVinculado INT FOREIGN KEY REFERENCES Usuarios(UsuarioId) NOT NULL
);

